### ISSUE TITLE
Question about emulation

### ISSUE THREAD

**Issue by morrowd** [DissectMalware/MDIExtractor#1]
Not an issue more of a question about the emulator/emulation. Is this project and the underlying XLMMacroDeobfuscator, actually executing the macro or strictly emulating it without code execution on the host. Thanks.

**Comment by DissectMalware** [comment]
The XLMMacroDeobfuscator does not execute any code on the machine; it is an XLM emulator.

When you run XLMMacroDeobfuscator on dridex samples, you can get the embedded HTA files (nothing can go wrong until this point)

dirdex_extractor.py extracts a part of vbscript in these HTA files and tries to translate it to python code. **Then dirdex_extractor uses eval function in Python to evaluate it. At this point, things can go wrong if malicious actor targets users of dridex_extractor.py**.

Hope this clarifies things.

**Comment by morrowd** [comment]
Yes, it clarifies things perfectly! Thanks for the quick and detailed response.
